/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mi.calculadora;

/**
 *
 * @author joer
 */
public class CalculadoraUI extends javax.swing.JFrame {
    private Valor calculador;
    private Operacion operador;
    private int id_operacion;
    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
        this.calculador = new Valor();
        this.operador = new Operacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbvisor = new javax.swing.JLabel();
        jbt7 = new javax.swing.JButton();
        jbt8 = new javax.swing.JButton();
        jbt9 = new javax.swing.JButton();
        jbtBorra = new javax.swing.JButton();
        jbt4 = new javax.swing.JButton();
        jbt5 = new javax.swing.JButton();
        jbt6 = new javax.swing.JButton();
        jbtSuma = new javax.swing.JButton();
        jbt1 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jbt3 = new javax.swing.JButton();
        jbtResta = new javax.swing.JButton();
        jbtMultiplica = new javax.swing.JButton();
        jbtDivide = new javax.swing.JButton();
        jbtIgual = new javax.swing.JButton();
        jbt0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbvisor.setBackground(new java.awt.Color(153, 255, 153));
        lbvisor.setFont(new java.awt.Font("Courier", 0, 48)); // NOI18N
        lbvisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbvisor.setText("0");
        lbvisor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        lbvisor.setOpaque(true);

        jbt7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt7.setText("7");
        jbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt7ActionPerformed(evt);
            }
        });

        jbt8.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt8.setText("8");
        jbt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt8ActionPerformed(evt);
            }
        });

        jbt9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt9.setText("9");
        jbt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt9ActionPerformed(evt);
            }
        });

        jbtBorra.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtBorra.setText("BORRAR");
        jbtBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBorraActionPerformed(evt);
            }
        });

        jbt4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt4.setText("4");
        jbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt4ActionPerformed(evt);
            }
        });

        jbt5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt5.setText("5");
        jbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt5ActionPerformed(evt);
            }
        });

        jbt6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt6.setText("6");
        jbt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt6ActionPerformed(evt);
            }
        });

        jbtSuma.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtSuma.setText("+");
        jbtSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSumaActionPerformed(evt);
            }
        });

        jbt1.setAction(jbt1.getAction());
        jbt1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt1.setText("1");
        jbt1.setName("bt1"); // NOI18N
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });

        jbt2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt2.setText("2");
        jbt2.setName("bt2"); // NOI18N
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });

        jbt3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt3.setText("3");
        jbt3.setName("bt3"); // NOI18N
        jbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt3ActionPerformed(evt);
            }
        });

        jbtResta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtResta.setText("-");
        jbtResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRestaActionPerformed(evt);
            }
        });

        jbtMultiplica.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtMultiplica.setText("*");
        jbtMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMultiplicaActionPerformed(evt);
            }
        });

        jbtDivide.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jbtDivide.setText("/");
        jbtDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDivideActionPerformed(evt);
            }
        });

        jbtIgual.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbtIgual.setText("=");
        jbtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIgualActionPerformed(evt);
            }
        });

        jbt0.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jbt0.setText("0");
        jbt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt0ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbvisor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(layout.createSequentialGroup()
                                            .add(jbt7)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jbt8)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jbt9))
                                        .add(layout.createSequentialGroup()
                                            .add(jbt4)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jbt5)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jbt6)))
                                    .add(layout.createSequentialGroup()
                                        .add(jbt1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jbt2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jbt3)))
                                .add(77, 77, 77))
                            .add(layout.createSequentialGroup()
                                .add(jbt0)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jbtBorra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtIgual)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtDivide, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtMultiplica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtResta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jbtSuma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(lbvisor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jbt7)
                            .add(jbt8)
                            .add(jbt9))
                        .add(19, 19, 19)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jbt4)
                            .add(jbt5)
                            .add(jbt6))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jbt2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jbt3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jbt1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jbt0)
                            .add(jbtBorra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(jbtSuma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtResta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtMultiplica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtDivide, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(28, 28, 28)
                        .add(jbtIgual)))
                .add(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt7ActionPerformed
        this.calculador.nuevaCifra(this.jbt7.getText());
        this.lbvisor.setText(calculador.mostrarNumero());
        
    }//GEN-LAST:event_jbt7ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        this.calculador.nuevaCifra(this.jbt2.getText());
        this.lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        this.calculador.nuevaCifra(this.jbt1.getText());
        this.lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt3ActionPerformed
        calculador.nuevaCifra(jbt3.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt3ActionPerformed

    private void jbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt4ActionPerformed
        calculador.nuevaCifra(jbt4.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt4ActionPerformed

    private void jbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt5ActionPerformed
        calculador.nuevaCifra(jbt5.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt5ActionPerformed

    private void jbt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt6ActionPerformed
        calculador.nuevaCifra(jbt6.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt6ActionPerformed

    private void jbt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt8ActionPerformed
        calculador.nuevaCifra(jbt8.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt8ActionPerformed

    private void jbt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt9ActionPerformed
        calculador.nuevaCifra(jbt9.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt9ActionPerformed

    private void jbt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt0ActionPerformed
        calculador.nuevaCifra(jbt0.getText());
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbt0ActionPerformed

    private void jbtBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBorraActionPerformed
        calculador.resetNumero();
        operador.borrarAcumulado();
        lbvisor.setText(calculador.mostrarNumero());
    }//GEN-LAST:event_jbtBorraActionPerformed

    private void jbtSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSumaActionPerformed
        operador.establecerAcumulado(calculador.obtenerNumero());
        calculador.resetNumero();
        id_operacion = 1;
    }//GEN-LAST:event_jbtSumaActionPerformed

    private void jbtRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRestaActionPerformed
        operador.establecerAcumulado(calculador.obtenerNumero());
        calculador.resetNumero();
        id_operacion = 2;
    }//GEN-LAST:event_jbtRestaActionPerformed

    private void jbtMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMultiplicaActionPerformed
        operador.establecerAcumulado(calculador.obtenerNumero());
        calculador.resetNumero();
        id_operacion = 3;
    }//GEN-LAST:event_jbtMultiplicaActionPerformed

    private void jbtDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDivideActionPerformed
        operador.establecerAcumulado(calculador.obtenerNumero());
        calculador.resetNumero();
        id_operacion = 4;
    }//GEN-LAST:event_jbtDivideActionPerformed

    private void jbtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIgualActionPerformed
        switch (id_operacion) {
            case 1: operador.suma(calculador.obtenerNumero());
                    break;
            case 2: operador.resta(calculador.obtenerNumero());
                    break;
            case 3: operador.multiplica(calculador.obtenerNumero());
                    break;
            case 4: operador.divide(calculador.obtenerNumero());
                    break;
            default: break;
        }
        lbvisor.setText(operador.mostrarAcumulado());
        calculador.establecerNumero(lbvisor.getText());
    }//GEN-LAST:event_jbtIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt0;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JButton jbt3;
    private javax.swing.JButton jbt4;
    private javax.swing.JButton jbt5;
    private javax.swing.JButton jbt6;
    private javax.swing.JButton jbt7;
    private javax.swing.JButton jbt8;
    private javax.swing.JButton jbt9;
    private javax.swing.JButton jbtBorra;
    private javax.swing.JButton jbtDivide;
    private javax.swing.JButton jbtIgual;
    private javax.swing.JButton jbtMultiplica;
    private javax.swing.JButton jbtResta;
    private javax.swing.JButton jbtSuma;
    private javax.swing.JLabel lbvisor;
    // End of variables declaration//GEN-END:variables
}
